test:
	ocamlbuild -use-ocamlfind tests.byte && ./tests.byte

play:
	ocamlbuild -use-ocamlfind main.byte && ./main.byte

play_ai:
	ocamlbuild -use-ocamlfind run_ai.byte && ./run_ai.byte

clean:
	ocamlbuild -clean

